package hackerRank.hackerRankInAString;

import java.io.*;
import java.util.*;
import java.text.*;
import java.math.*;
import java.util.regex.*;
import java.util.stream.Collectors;

public class Solution {

    private static String hackerrankInString(String s) {

        String requiredString = "hackerrank";
        char[] requiredChars = requiredString.toCharArray();
        char[] checkedChars = s.toCharArray();
        int counter = 0;
        int tmpIndex = 0;
        for (char requiredChar : requiredChars) {
            for (int j = tmpIndex; j < checkedChars.length; j++) {
                if (requiredChar == checkedChars[j]) {
                    System.out.print(checkedChars[j]);
                    counter++;
                    tmpIndex = j + 1;
                    break;
                }
            }
        }

        if (counter == requiredString.length()) return "YES";
        else return "NO";
    }

    public static void main(String[] args) {

        System.out.println(hackerrankInString("bvxqokorcxbivcnvdmcametgxvzftjkiyzatzatnapwttpxwqegvxllbtvxfnmwwbkicnaxmjxwgecexnndlgmwfsiusksumczuzfpajpmsboatncwzecbkxavloimnkllziuvaikvogykbcqizbqmdxyipclavzgvgonstdzpzskwvixgdfyblmmymtxwoxsoyqlqzbsyuatyebgkwznlnxqjefgkeluqcvtgmtvjsbaalxpqdmkptbqyefleiulcbsijglnawbwmbzuqybuqfmpewqnvnxqpawngtmuplfvlctyysbicubvnbjaayepapsotfzzfpdifsnpovufuuxsevipbbylkyoboqjatntvtqpbxjgposuleiqjnzbdecuzdjujweuztnwoggaoljoniwpkdbttjpnfomegodafcqpfjoxcpaiejdnnkvavjxgnbffuzkaozveqekvmdvwfnldlpzbkyioczsqnggspqgeyktlksupywxkgydwzovlndectcjwnxikuwcqdapqlvsdlboaesypkpujcdmwqmvfoqlsptkkzwsmauadiuqoygoucdzcgoodmdmwcaafwygzktolpqzvyovekgpobndncyzmpemzsxtzovjxzettonibczyyxdfvbealnzsoysminakkcwlmnnxnlultsnagfllmckenvbyimcmxsxkwfxcozjniayaydmausxgwntoxplvmnbqmgnbqibbksgxzjydswmdlmxdcjzszicsowtnntakaopldgywibqdbiapexeumwizozfdjzdjfevwkycctuoplypfvnlclilayfgntuaidctvxntujlaqzizoiueqgkydnzqfeaizobbniyswfaooxuzxfcuvsplksvgqnpitctdkymlytpxtzikveznmvzakpiecagzilefzluzfxexzwiwcfmwfgbvumcalixagmikxgdwjdblzlowyximkgwtwgkcycluaiuddfocelymvfccfbwykfobxpuwxkbppsgyndquubdvtmzjfeoiddeydndzpciidysilvtmtfjiejaodwakwbmqgcgklvljfykmglvikblmdyynxuigxgkujcjtenjgpdimocywaxfwqusyzpytwxpvsbxqqqjbcvzqfmppaixnofygmxilxijxzyxgmfjiosgxasfbnanzqawmiuzdpbygzussrymjsbdjwsxzxxpjzskoqqslqwxlnvqycqtmsklyywuqfdkfofwtoeccajywebpwwxydjvqcdgaaztmxntemvlqxpsstzlzullnpxbyjywstjelfjeizvzjfguimgoacptxioauqiqkabptbsebcdzctdtyqapbjastgmlvoekosvkfbzfbnwkoiytspdkeoywpaajkqvlgvjqqgdomywcsgojgkiewjcytaskqgloqtdjbssfjdcgxmjtsbmmgkbdakxclflnmadmbnzljqqunuwwvvquxjtiiazivxoogvbmpajvbtclkjjyjovbstpvgspigyctgcbxxockkvlzllftwzbnlpnjxoppkluqoxkpaauipgndpixfeqyucgtyqfngemdnyfywiyafxtcfypgcvslwmzxtmxqljdcxibsfctqsgipwqjcvkcziwjeyzkjocynfmbwmokmkbitlxceucgksjytasldlngbvzegokdppywngxululnxvxcuiffgiyzjbfqfkfdnqwtmaknebokdistbgvunmdfdplxfosoixqcaalexpnvffaxtzmdafsczxbtwejnabxiugiecdjvjaduyswnqmgogjsnqajqjvekonsfamdiblvwidimdkblpbzcubdieztmmyibdzaoljbaiptpvqaofgnxcuwmycdqijtwonoivfxjdayagywnazkzgmlcdwcjvssyjndebotuybwkffvazpbcddkgoqjtqtpxljosfcsebmoyajqagcfpngmjfcsjgnzcmlftngnococzvnybagwdfgmnvlcsuyxniomxqcmaebfadlopzcznepbixvkxxvvsajitzxcvvbezmbnglkwsnmqxecgfjxcvzsysokyewupakmfjjtwjiqwexitgoznwtimxzgewskdmicmgmpoekeypqusfitatpfovzlgkgxizbntbjqpcafpzuwocpkyjguoqmcnpeivbdqldcqkawikuvkmdbqvaikitakpyfvgacxtiijcvjijaowtmixlcoocdwgkeajvyfktgjwzzanxclapampbxgbmtetngyyumkemiqiggfxvoubsiemjwfyjzwlsxqfpotdbpusluexmuwkyzqsjlsloldiqyjblpsujxtfeeixluktalimfdiiwubqvdsmbbjxzcvdqtgbtevmlkolmnsiydxuaaubulnzscoopuqakwnnwgnvpignakbpwkgapuwuawdmdactluoovbbotgbafszbgukovsdnknakzyczlzqvqmeenpiyywcioanbbqffscplmntvaspeqaqmlxjywonjenoozpqebjliftfmlbeymayspcyllcetbtmoidbmwdonfnuxpttqbaoeiweykwtuakmajwlzuymbbcxcnnxezkzypyqaufbxziyfyggsfkjyjzlqqxnuypvimvwbbxwlavxjninvxjyddejclcaodwfucdsmkccvaoynvsficxzdnmyvfbdotsmncicjnsiqafizvibgqeapntkniagampbckuuezbnydoplvgjejqtilxajfqkkpxcdpyqbeiisucqybscyscscpaaqyvgmcmcijtwmkiaozeluxvukxbmizpxndyjxsuiaizawtxwoqjpugizvufwjvxscoeiqzdcqmcisckkskpzovfeukzdamjilzedgpbnddstwoblwevduslwgxqvttjesioswkfgojkmdzgytvuugewesjgquvcdkuokzieaizeenqdazmeobcofxgldvkxqiewulyaqzxejbkpayjcywmaeuoxfgtdymvenxmfiqbvdzissqampwpooovsoiflpoqydauotdkqjefzqtuogaftyjmpuuxkqgkaczwisyctlbqzsjusmapxtsyucsjzswbfcnqgzeasffawejjmvkaofoigkxzawcbfwvfejndvtokcljtdbsuieiqjnbesgbsjvslinnankqdobkkszaeknuddvuvgggdcyezlogexcpeqxuowjiwzvbliiymtbdlkltsimlxnaunaywzgjczuymtwtekdcnjwadoxcbfjdqmdnevjglqmamkdmabmmpigwtkgexknzqjdbtgvbzddvxvqqemnutoolglfjpkiuusilpqstsgvomtbgzcngfcjcdvviafqstxulqxqtwiulbmnqbfbvwsbkrgcmoifvfbtwfwjgsvaokzbicqxgpjopgyasxtcpyfylvodvtvfgsefulctkvwwyvlyngblgbbsnimeduwtsljfivqstkucdsgtwfpmdpeysogolimyquyaqegdgzmtecdjvkoudddglgloknwetevoylfmuyzlyzmbnmidwqfjzfvqfsnyujzvowbeaaxwexxoxbbacbxwjmxycocsjeywkinejdzvqoqwuygaibgtqjgfcntykovlnpgkexaegtgtkbdnqybbyxyuolewqzmiygtgjjydkdwzuobxnmsyfvknpxtpjliokwiubfdmdyzuwwcbovzzzzvinosvytlkospmtoffymqqxpfvlgzuwvbpkxmtkoulfqtepxnymktekecsbcjjepfkfymtknlsimdskbqblggvdsjmbeddyfqgydjocitgyaxfetweuqgddjblftvntcvsyfiaocolgwzcwnaxjmknejyfqbcmnpxobbometbyxndxxvxoiizxtdtwziwnaytyjdibyiknunywxabvoobxvdqvdwefywecgcqtcdjwelycezpvepjqosglnwpmmvzkbeifdzwgjytespluszuwvqdtfxldyaqudvfeuybfyjvxsxsedmppkmgcpbgjlsqzsmijmnzawagoiegjjvacxbczbyauuntdyqabsfgdoxptqxlpdgkunovezpaadvynncqdsdxxjnzqyfluujkjemxnxqpklbnzluaxwjubjmfvnkfwsxefmvabfeuvnfzioulufpzanmkkdbnvuelxugxngbezvyqcibeiudkvieaklzddeugnypwfebgpzxoqbpwoxwtmdvjfzvwncdosekzffuifkjyakdjpuypsdkvkgasqffxzqkmpmuejxgwcoppuidbgecndopibdotpdxkslywmcfaetmsxdkwypybggasmlwqjmvnlbivxketutvxpwvgbzfgpmsvcvvtwkloeljxalxzzfgbbcllopakazjvzgqadvllywpxamyodlvvqmpqgfbmcalnmzkqznflwvfzzaxdoyeczavqwpxuxglulkeaqumbdyzoutwtkbneoxlqlkleeotwtydzdcqipgyfdecjpyfvgzzmekmtlisyaldogvpwcqjdsgwucptuaibvntpukmgvjjansjkmpylvexmqgysjnwqnwudoqoquflcqyzffewolymmosbxvcgbnaauxopkllslgeguzngxszbkbdvfnvaitxtaimctciiydovnnffaamfvtawoqazqkdnpwuxkvxfapbogupbfoguzdivsxuyvdgyvwkcvkoptkdiunguslfafuoixcvwgxauqjnpfimlkavqpdomyiefhoisfujicsxglubqntfamsndkvgviukzfoxipwgtuewjpnzpllfmsilwgbvoajuydsnjollmljygoqfjujazlgxdwbwoiywlejidwjigiftnnbfnxzqvqyempksflipedanfpxknvmzezpfytiwwoadjfibznntgwtwwkkvqvdoqpysbfmbzkcxiwqftcgpwobcsefynfsxmsjmnlspimoftwcxkmzvudzgydagjajfdvnlgsybafzmccsykpjpvuekxkgkcfdniecdoquugwegimkdioekyubebqlwwuszbiynpwffeybuuiomwwsdppdneuunjgxktscgzzyqgwlesywoibkfidnogmgbtasxleelkxtecwssjusbcptnggtvxpincqvujktpzhm"));

    }
}